# Generated by Django 4.2.4 on 2023-08-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleatrentalstation',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.rentalstation'),
        ),
    ]
